name: bayesian-stats-modelling-tutorial
channels:
- conda-forge
dependencies:
- python=3.8
- jupyter
- conda
- ipython
- ipykernel
- numpy
- matplotlib
- scipy
- pandas
- pymc3
- arviz
- pip
- pre-commit
- black
- nbstripout
- mypy
- flake8
- pycodestyle
- pydocstyle
- pip:
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mknotebooks
